### ISSUE TITLE
Card selection & placement bugs

### ISSUE THREAD

**Issue by vasukas** [team-plover/warlocks-gambit#6]
* player's cards don't fit in window with aspect ratio narrower than 16:9;
  * btw "Make exactly 16:9" button doesn't work on maximized window
* selection isn't working properly between cards (in video cursor is moving in one direction);

https://user-images.githubusercontent.com/51795831/156447902-29c42ee2-8fb7-40bd-a522-690b8c084194.mp4

**Comment by nicopap** [comment]
Here is a definite fix for the card placement:

Create two invisible shapes centered on the wrist, they would be `RayCastMesh`es with a different `RayCastSet` than the one of the cards:
* One small, going only up to the base of the thumb. While this is hovered, the hand is raised to reveal the sleeve to drop the card in
* One large that encompasses the whole hand and all the cards, if we drop the card while hovering this, the card goes back to the hand
